# Generated by Django 4.1 on 2022-08-29 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0002_glucose_aufzeichnungstyp_glucose_glukosewert_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glucose",
            options={"verbose_name": "Glucose", "verbose_name_plural": "Glucose"},
        ),
        migrations.AddField(
            model_name="glucose",
            name="gerätezeitstempel",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
