# Generated by Django 4.1 on 2022-08-29 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0003_alter_glucose_options_glucose_gerätezeitstempel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucose",
            name="gerätezeitstempel",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
