# Generated by Django 4.1 on 2022-08-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0004_alter_glucose_gerätezeitstempel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glucose",
            old_name="gerätezeitstempel",
            new_name="date",
        ),
    ]
