# Generated by Django 4.1 on 2022-08-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0005_rename_gerätezeitstempel_glucose_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glucose",
            old_name="date",
            new_name="gerätezeitstempel",
        ),
    ]
