# Generated by Django 4.1 on 2022-08-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0007_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucose",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="glucose.userprofile"
            ),
        ),
    ]
