# Generated by Django 4.1 on 2022-08-29 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("glucose", "0009_alter_glucose_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glucose",
            name="aufzeichnungstyp",
        ),
        migrations.RemoveField(
            model_name="glucose",
            name="gerät",
        ),
        migrations.RemoveField(
            model_name="glucose",
            name="gerätezeitstempel",
        ),
        migrations.RemoveField(
            model_name="glucose",
            name="glukosewert",
        ),
        migrations.RemoveField(
            model_name="glucose",
            name="seriennummer",
        ),
        migrations.AddField(
            model_name="glucose",
            name="device",
            field=models.CharField(default=1, max_length=200, verbose_name="Gerät"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="glucose",
            name="device_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Gerätezeitstempel"
            ),
        ),
        migrations.AddField(
            model_name="glucose",
            name="glucose_level",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="Verlauf mg/dL", verbose_name="Glukosewert"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="glucose",
            name="recording_type",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Aufzeichnungstyp"
            ),
        ),
        migrations.AddField(
            model_name="glucose",
            name="serial_number",
            field=models.CharField(
                default=1, max_length=200, verbose_name="Seriennummer"
            ),
            preserve_default=False,
        ),
    ]
