# Generated by Django 4.1 on 2022-08-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "glucose",
            "0011_alter_glucose_device_alter_glucose_device_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucose",
            name="glucose_level",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
